# ---- Dataset form first SoMeR version ----

# --- !Ups
INSERT INTO `designationdata` (`designationdata_id`, `designation_name`, `designation_category`, `designation_subcategory`, `designation_description`) VALUES
	(1, 'Discuss /comment on publications within the platform', 'Functions that allow scientific communication (sorted by purpose)', 'Networking and collaboration\n', NULL),
	(2, 'Follow users / network building', 'Functions that allow scientific communication (sorted by purpose)', 'Networking and collaboration\n', NULL),
	(3, 'Create / follow groups or projects', 'Functions that allow scientific communication (sorted by purpose)', 'Networking and collaboration\n', NULL),
	(4, 'Working in groups (e.g. Exchanging publications, saving notes in the uploaded PDF)', 'Functions that allow scientific communication (sorted by purpose)', 'Networking and collaboration\n', NULL),
	(5, 'Send / receive inquiries (e.g. author versions of publications), send private messages (mailbox)', 'Functions that allow scientific communication (sorted by purpose)', 'Networking and collaboration\n', NULL),
	(6, 'Release status messages', 'Functions that allow scientific communication (sorted by purpose)', 'Networking and collaboration\n', NULL),
	(7, 'Consult the community', 'Functions that allow scientific communication (sorted by purpose)', 'Networking and collaboration\n', NULL),
	(8, 'Blogs or other functionalities connecting the platform operators with the users so that the operators can get feedback from platform users or explain new features', 'Functions that allow scientific communication (sorted by purpose)', 'Networking and collaboration\n', NULL),
	(9, 'Upload of full texts or other content', 'Functions that allow scientific communication (sorted by purpose)', 'Publication and dissemination', NULL),
	(10, 'Download of full texts or other content', 'Functions that allow scientific communication (sorted by purpose)', 'Publication and dissemination', NULL),
	(11, 'Web Importer', 'Functions that allow scientific communication (sorted by purpose)', 'Publication and dissemination', NULL),
	(12, 'Export of bibliographic data in other formats (e.g. BibTeX)', 'Functions that allow scientific communication (sorted by purpose)', 'Publication and dissemination', NULL),
	(13, 'Share / reshare publications (via additional Social Media, e.g. Facebook, Twitter)', 'Functions that allow scientific communication (sorted by purpose)', 'Publication and dissemination', NULL),
	(14, 'Forwarding of publications to peers / magazines (i.e. proposals for publications)', 'Functions that allow scientific communication (sorted by purpose)', 'Publication and dissemination', NULL),
	(15, 'Saving of publications with link (Social Bookmarking)', 'Functions that allow scientific communication (sorted by purpose)', 'Publication and dissemination', NULL),
	(16, 'Quoting publications with reference to different quotation styles', 'Functions that allow scientific communication (sorted by purpose)', 'Publication and dissemination', NULL),
	(17, 'Open review / evaluation (e.g. giving ratings for publications)', 'Functions that allow scientific communication (sorted by purpose)', 'Publication and dissemination', NULL),
	(18, 'Creation of a user profile with CV and / or other documents and export of user profiles as CV', 'Functions that allow scientific communication (sorted by purpose)', 'Self-Marketing', NULL),
	(19, 'Present own skills and expertise on own user profile', 'Functions that allow scientific communication (sorted by purpose)', 'Self-Marketing', NULL),
	(20, 'Integration of the user profile on other websites', 'Functions that allow scientific communication (sorted by purpose)', 'Self-Marketing', NULL),
	(21, 'Statistiscs for user profiles / rankings', 'Functions that allow scientific communication (sorted by purpose)', 'Self-Marketing', NULL),
	(22, 'View of advertisements and applications for jobs', 'Functions that allow scientific communication (sorted by purpose)', 'Self-Marketing', NULL),
	(23, 'Publication of job advertisements', 'Functions that allow scientific communication (sorted by purpose)', 'Self-Marketing', NULL),
	(24, 'Social actions: insert options or icons that allow interfaces between the platforms or services', 'Impact of platforms or social media services in the scientific community', 'Interactions between services', NULL),
	(25, 'Activities analyzed by *metrics aggregators ', 'Impact of platforms or social media services in the scientific community', '*metrics analyzed', NULL),
	(26, 'APIs from platforms (URL)', 'Impact of platforms or social media services in the scientific community', 'APIs & limits', NULL),
	(27, 'APIs\' limits', 'Impact of platforms or social media services in the scientific community', 'APIs & limits', NULL),
	(28, 'Data integrated in Altmetric Explorer (altmetric.com)', 'Tools and sources - Data aggregators', 'Commercial data providers', NULL),
	(29, 'Dimensions', 'Tools and sources - Data aggregators', 'Commercial data providers', NULL),
	(30, 'Data integrated in Kudos', 'Tools and sources - Data aggregators', 'Commercial data providers', NULL),
	(31, 'Data integrated in PlumX (Plum Analytics)', 'Tools and sources - Data aggregators', 'Commercial data providers', NULL),
	(32, 'Data integrated in Impactstory.org', 'Tools and sources - Data aggregators', 'Non-commercial data providers (open source)', NULL),
	(33, 'Data integrated in Depsy.org (ImpactStory)', 'Tools and sources - Data aggregators', 'Non-commercial data providers (open source)', NULL),
	(34, 'Data integrated in Lagotto (general)', 'Tools and sources - Data aggregators', 'Non-commercial data providers (open source)', NULL),
	(35, 'Data integrated in PLOS (implementation von Lagotto)', 'Tools and sources - Data aggregators', 'Non-commercial data providers (open source)', NULL),
	(36, 'Data integrated in VIVO', 'Tools and sources - Data aggregators', 'Non-commercial data providers (open source)', NULL),
	(37, 'Data integrated in VZG (implementation von Lagotto)', 'Tools and sources - Data aggregators', 'Non-commercial data providers (open source)', NULL),
	(38, 'Data Integrated in Webometric Analyst 2.0', 'Tools and sources - Data aggregators', 'Non-commercial data providers (open source)', NULL);

# --- !Downs
DELETE FROM `designationdata`;