# ---- Dataset form first SoMeR version ----

# --- !Ups
INSERT INTO `platformdata` (`platformdata_id`, `platform_name`, `platform_or_service_type`, `target_group`, `commercial_or_noncommercial_service`, `free_or_subscription_source`, `primary_purpose`, `geographical_reach`, `number_active_or_registered_users`, `content_coverage`, `website_url`, `usage_ranking`, `description`) VALUES
	(1, 'Academia.edu', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(2, 'Airity Library', 'Search platform of academic ressources', 'academic', '', '', 'reference management', 'China and Taiwan', 'not found', 'academic journal articles, doctoral dissertations and conference paper compliations', 'http://www.airitilibrary.com/', NULL, NULL),
	(3, 'Arnetminer', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(4, 'Bibsonomy', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(5, 'CiteULike', 'social reference management service', 'academic', 'non-commercial', 'free (gold option available for more features, 30 GBP per year)', ' to store, organise and share the scholarly papers you are reading', 'worldwide', 'ca. 208.000 registered users (Ortega, L. J., 2016, Social Network Sites for Scientists: A Quantitative Survey. Chandos Publishing).', '8,641,673 articles', 'http://www.citeulike.org/', NULL, NULL),
	(6, 'Dailymotion', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(7, 'del.icio.us', '', '', '', '', 'reference management', '', '', '', '', NULL, NULL),
	(8, 'Dryar (repository)', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(9, 'Epernicus', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(10, 'EBSCO', 'discovery service provider', 'libraries', 'commercial (EBSCO Industries Ltd.)', 'subscription', 'provider of research databases, e-journals, magazine subscriptions, e-books and discovery service to libraries (academic and other)', 'worldwide', '', '375 full-text databases, a collection of 600,000-plus ebooks, subject indexes, point-of-care medical references, and an array of historical digital archives', 'https://www.ebsco.com/', NULL, NULL),
	(11, 'F1000', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(12, 'F1000Prime', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(13, 'Facebook', '', 'non-academic', '', '', 'social network', '', '1.23 billion daily active users on average for December 2016 (http://newsroom.fb.com/company-info/ as of 02/19/2017)', '', 'www.faceboo.com', NULL, NULL),
	(14, 'Figshare', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(15, 'GitHub', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(16, 'Google Scholar', 'bibliographic database', 'academic', 'commercial (Google Inc.)', 'free', 'web search engine, indexing service for full text or metadata of scholarly articles (papers, not journals)', 'worldwide: articles from a wide variety of sources in all fields, all countries, and over all time periods', 'not found', 'journal and conference papers, theses and dissertations, academic books, pre-prints, post-prints, abstracts, technical reports or their drafts and other scholarly literature from diverse areas of research, court opinions and patents. Sources:  web crawling, individual authors, university repositories, journal publishers', 'scholar.google.com', NULL, NULL),
	(17, 'Google+', 'social network service', 'non-academic', 'commercial (Google Inc.)', 'free', 'social network; social layer for other Google services', 'worldwide; except from mainland China and Iran', 'about 400 million active users (https://www.statisticbrain.com/google-plus-demographics-statistics/)', 'unknown', 'https://plus.google.com', NULL, NULL),
	(18, 'Instagram', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(19, 'iTunes', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(20, 'Jabber', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(21, 'JSTOR', 'digital library', 'academic', 'nonprofit (ITHAKA)', 'subscription (free or low-cost for Africa and developing countries)', 'selective digital library of academic content including top peer-reviewed journals, respected literary journals, academic monographs, research reports from trusted institutes, and primary sources', '> 8,000 institutions in more than 160 countries had access (as of 2013)', '> 8,000 institutions in more than 160 countries had access (as of 2013)', '10 million academic articles from 2.000 journals, 50.000 books, and 2 million primary source documents in 75 disciplines from 1.200 publishers', 'https://www.jstor.org/', NULL, NULL),
	(22, 'LinkedIn', 'social network service', 'non-academic', 'commercial (Microsoft)', 'free and subscrition (premium services)', 'professional networking: business- and employment-oriented service', '>200 countries and territories, access in 24 languages. Highest number of users in USA, Brazil, Great Britain and Canada', '467 million users (members), 106 million monthly active users, 1.5 million groups', 'focus on public professional profiles for promoting visibility, networking (users) and recruiting (companies). Options for adding, editing, or removing publications, video options', 'www.linkedin.com', NULL, NULL),
	(23, 'Mendeley', '', 'academic', '', '', 'reference management, research network', '', 'over 6 million researchers worldwide https://www.mendeley.com/ as of 02/19/2017)', '', 'www.mendeley.com', NULL, NULL),
	(24, 'MyNetResearch', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(25, 'mysciencenetwork.com', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(26, 'MySpace', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(27, 'Nature (Blogs)', '', '', '', '', 'journal comments', '', '', '', 'http://blogs.nature.com/ ', NULL, NULL),
	(28, 'Nature (OpenSearch)', '', '', '', '', 'journal comments', '', '', '', '', NULL, NULL),
	(29, 'OpenEdition', '', '', '', '', 'journal comments', '', '', '', '', NULL, NULL),
	(30, 'Pinterest', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(31, 'PLOS (full-text)', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(32, 'PubMed Commons (Central)', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(33, 'PubPeer', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(34, 'Reddit', '', '', '', '', 'journal comments', '', '', '', '', NULL, NULL),
	(35, 'RePEc', 'preprint repository', 'academic', 'non-commercial', 'mostly free', 'preprint repository, dissemination of scholarly research, indexing and ranking authors/ research organizations', '95 countries', 'over 50.000 authors, over 75.000 email subscriptions', 'about 2.3 million research pieces from 2,800 journals and 4,500 working paper series', 'http://repec.org/', NULL, NULL),
	(36, 'ResearchBlogging.org', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(37, 'ResearchGate', 'academic network service', 'academic', 'commercial (ResearchGate GmbH)', 'free ', 'research network: members share projects, research output and collaborate with their peers', 'worldwide: 193 countries', '13+ million members', '100+ mio publications: Articles, Books, Chapters, Codes, Conference Papers, Cover Pages, Data Sets, Experiment Findings, Methods, Negative Results, Patents, Posters, Presentations, Raw Data, Research Proposals, Technical Reports, Thesis, Working Papers, Figures and media files, Unpublished articles and working copies/\nMembers by discipline: 15% Medicine, 14% Biology, 14% Engineering, 7% Chemistry, 6% Comp. Science, 4% Physics, 40% Other  ', 'www.researchgate.net', NULL, NULL),
	(38, 'Scholastica', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(39, 'Sciblogs.com', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(40, 'ScienceDirect', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(41, 'ScienceSeeker', '', 'academic', '', '', 'research blogging', '', '', '', '', NULL, NULL),
	(42, 'ScienceStage', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(43, 'Slack', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(44, 'SlideShare', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(45, 'SourceForge', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(46, 'SSRN', 'preprint repository', 'academic', 'commercial\n(Elsevier)', 'free', 'preprint repository, dissemination of scholarly research', '140 countries by SSRN\'s email abstract eJournals', '>2.2 Million', '361,685 Authors, 776,247 Abstracts, 656,786 Full Text Papers, 66,189 Papers received (last 12 months)', 'https://www.ssrn.com/', NULL, NULL),
	(47, 'Stack Overflow', 'A question-and-answer website', 'non-academic', 'commercial (Stack Exchange, Inc)', 'free', 'Questions and answers related to computer programming', '', '8,501,964 registered and unregistred users (https://stackexchange.com/sites#), 226357 registered users (https://stackoverflow.com/users?tab=reputation&filter=all) ', '15,460,642 questions, and 24,036,862 answers', 'https://stackoverflow.com/', NULL, NULL),
	(48, 'Tumblr', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(49, 'Twitter', '', 'non-academic', '', '', '(research) blogging', '', '313 milion monthly active users (https://about.twitter.com/company as of 02/19/2017)', '', 'www.twitter.com', NULL, NULL),
	(50, 'Vimeo', 'Video hosting service', 'non-academic', 'commercial (Subsidiary of IAC)\n', 'Basic accounts are for free, Other types of membership have to pay on a monthly basis.', 'to upload, share and view videos', 'it is banned in Indonesia and China', 'More than\n35 million creators worldwide\n', ' there are 55,434,134 videos (short films and movies) as of 2015. ', 'https://vimeo.com/', NULL, NULL),
	(51, 'vk.com', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(52, 'Web of Science™', 'citation indexing service', 'academic', 'commercial (Clarivate Analytics)', 'subscription', 'research evaluation: access to selected scholarly literature in over 250 disciplines, access to cited reference connections and citation reports', 'worldwide, predominance of nordamerican, european and japanese research output in English. Regional databases: Latin America, China, Korea, Russia. Language specific database: Arabic', 'not found', 'Web of Science Core Collection: >18,000 peer reviewed journals, books and proceedings. 100% fully indexed cited references, authors and autor affiliations, 1.3 billion cited references going back to 1900', 'www.webofknoledge.com', NULL, NULL),
	(53, 'Weibo (Sina Weibo)', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(54, 'Wikipedia', 'general reference website', 'non-academic', 'non-commercial (Wikimedia Foundation)', 'free', 'multilingual Wiki of a free, collectively created encyclopedia', '299 language editions, over 43 million wiki pages. Largest editions: English, Cebuano, Swedish, German, Dutch and French', '>272,001 active users (one or more actions within a certain month), >10,151,406,947 registered users, 30,710,162 total users', 'diverse: anyone with internet access regardless of age, culture or background can contribute to the platform. Users can be contributors and make changes to Wikipedia articles. Contributions are more important than expertise or qualifications of the contributor', 'www.wikipedia.org', NULL, NULL),
	(55, 'WordPress Blogs', '', 'academic', '', '', 'research blogging', '', '', '', '', NULL, NULL),
	(56, 'XING', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(57, 'YouTube', 'video sharing service', 'non-academic', 'commercial (Google Inc.)', 'free', 'display of user-generated and corporate media videos (and audio recordings)', '95% of the Internet population, local versions in 88 countries, access in 76 languages', 'over a billion users', 'talks, webinars, presentations, academic interviews', 'www.youtube.com', NULL, NULL),
	(58, 'Zenodo', '', '', '', '', '', '', '', '', '', NULL, NULL),
	(59, 'Zotero', 'reference management service', 'academic', 'non-commercial (Center for History and New Media at George Mason University)', 'free (optional storage upgrades for 2-10$ per month)', 'reference management; plus very basic functionalities for document storage, collaboration and networking', 'supported in >30 languages', 'in 2014 the estimated number of accounts was between 1 and 1.5 million; but even Zotero\'s developers don\'t know exact figures (http://quintessenceofham.org/2011/05/21/on-usage-figures/)', 'in 2015, ~60% of the items in the Altmetric.com database had at least one entry in Zotero (https://www.zotero.org/blog/studying-the-altmetrics-of-zotero-data/)', 'http://www.zotero.org/', NULL, NULL);

# --- !Downs
DELETE FROM `platformdata`;